### ISSUE TITLE
运行 webui.py 时报错：AttributeError: 'dict' object has no attribute 'then'

### ISSUE THREAD

**Issue by shtdbb** [shengxia/RWKV_Role_Playing#11]
```
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading /root/project/rwkv/model/RWKV-4-Novel-3B-v1-Chn-20230412-ctx4096.pth ...
Strategy: (total 32+1=33 layers)
* cuda [float16, uint8], store 20 layers
* cuda [float16, float16], store 13 layers
0-cuda-float16-uint8 1-cuda-float16-uint8 2-cuda-float16-uint8 3-cuda-float16-uint8 4-cuda-float16-uint8 5-cuda-float16-uint8 6-cuda-float16-uint8 7-cuda-float16-uint8 8-cuda-float16-uint8 9-cuda-float16-uint8 10-cuda-float16-uint8 11-cuda-float16-uint8 12-cuda-float16-uint8 13-cuda-float16-uint8 14-cuda-float16-uint8 15-cuda-float16-uint8 16-cuda-float16-uint8 17-cuda-float16-uint8 18-cuda-float16-uint8 19-cuda-float16-uint8 20-cuda-float16-float16 21-cuda-float16-float16 22-cuda-float16-float16 23-cuda-float16-float16 24-cuda-float16-float16 25-cuda-float16-float16 26-cuda-float16-float16 27-cuda-float16-float16 28-cuda-float16-float16 29-cuda-float16-float16 30-cuda-float16-float16 31-cuda-float16-float16 32-cuda-float16-float16 
emb.weight                        f16      cpu  50277  2560 
blocks.0.ln1.weight               f16   cuda:0   2560       
blocks.0.ln1.bias                 f16   cuda:0   2560       
blocks.0.ln2.weight               f16   cuda:0   2560       
blocks.0.ln2.bias                 f16   cuda:0   2560       
blocks.0.att.time_decay           f32   cuda:0   2560       
blocks.0.att.time_first           f32   cuda:0   2560       
blocks.0.att.time_mix_k           f16   cuda:0   2560       
blocks.0.att.time_mix_v           f16   cuda:0   2560       
blocks.0.att.time_mix_r           f16   cuda:0   2560       
blocks.0.att.key.weight            i8   cuda:0   2560  2560 
blocks.0.att.value.weight          i8   cuda:0   2560  2560 
blocks.0.att.receptance.weight     i8   cuda:0   2560  2560 
blocks.0.att.output.weight         i8   cuda:0   2560  2560 
blocks.0.ffn.time_mix_k           f16   cuda:0   2560       
blocks.0.ffn.time_mix_r           f16   cuda:0   2560       
blocks.0.ffn.key.weight            i8   cuda:0   2560 10240 
blocks.0.ffn.receptance.weight     i8   cuda:0   2560  2560 
blocks.0.ffn.value.weight          i8   cuda:0  10240  2560 
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blocks.31.ln1.weight              f16   cuda:0   2560       
blocks.31.ln1.bias                f16   cuda:0   2560       
blocks.31.ln2.weight              f16   cuda:0   2560       
blocks.31.ln2.bias                f16   cuda:0   2560       
blocks.31.att.time_decay          f32   cuda:0   2560       
blocks.31.att.time_first          f32   cuda:0   2560       
blocks.31.att.time_mix_k          f16   cuda:0   2560       
blocks.31.att.time_mix_v          f16   cuda:0   2560       
blocks.31.att.time_mix_r          f16   cuda:0   2560       
blocks.31.att.key.weight          f16   cuda:0   2560  2560 
blocks.31.att.value.weight        f16   cuda:0   2560  2560 
blocks.31.att.receptance.weight   f16   cuda:0   2560  2560 
blocks.31.att.output.weight       f16   cuda:0   2560  2560 
blocks.31.ffn.time_mix_k          f16   cuda:0   2560       
blocks.31.ffn.time_mix_r          f16   cuda:0   2560       
blocks.31.ffn.key.weight          f16   cuda:0   2560 10240 
blocks.31.ffn.receptance.weight   f16   cuda:0   2560  2560 
blocks.31.ffn.value.weight        f16   cuda:0  10240  2560 
ln_out.weight                     f16   cuda:0   2560       
ln_out.bias                       f16   cuda:0   2560       
head.weight                       f16   cuda:0   2560 50277 
/usr/local/Anaconda3/envs/music/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Button, please remove them: {'elem_classes': 'warn_btn'}
  warnings.warn(
Traceback (most recent call last):
  File "webui.py", line 26, in <module>
    app = ui.create_ui()
  File "/root/project/rwkv/RWKV_Role_Playing-master/modules/ui.py", line 267, in create_ui
    message.submit(self.__send_message, inputs=input_list + [action_front], outputs=output_list + interactive_list).then(self.__arrange_token, outputs=interactive_list, show_progress=False)
AttributeError: 'dict' object has no attribute 'then'
```
求教是什么问题呀，库都按要求安装了

**Comment by zhouquan9** [comment]
刚遇到了一样的问题，把gradio升级到3.21以上就好了

https://github.com/gradio-app/gradio/issues/3501
