### ISSUE TITLE
无法加载角色，读取角色配置报错

### ISSUE THREAD

**Issue by tjsky** [shengxia/RWKV_Role_Playing#27]
为了排除时本地软硬件问题导致的差异
使用colab在全默认运行（本地也存在一样问题）：

![_20230913232810](https://github.com/shengxia/RWKV_Role_Playing/assets/7272911/046ea63f-5e3b-4544-b0ec-a0faa4a97ab5)
载入角色（UI本身就很诡异）时报错如下

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/content/RWKV_Role_Playing/modules/ui.py", line 108, in __load_char
    with open(f"{self.char_path}/{file_name}.json", 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './chars/雪.json'
```
实际目录下文件结构为下图
![_20230913232911](https://github.com/shengxia/RWKV_Role_Playing/assets/7272911/c66b3cee-a4b8-41ea-84e2-0a76ebd96b53)

**Comment by tjsky** [comment]
gradio的锅，重新安装依赖更新gradio至最新版就好了
