### ISSUE TITLE
使用--cuda_on 1启用CUDA编译时提示找不到模块

### ISSUE THREAD

**Issue by leimm2002** [shengxia/RWKV_Role_Playing#4]
这是当时的报错信息：
```
Using C:\Users\Momozawa Chiyuki\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\Momozawa Chiyuki\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117\wkv_cuda\build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_cuda...
Traceback (most recent call last):
File "C:\RWKV\RWKV_Role_Playing\webui.py", line 17, in <module>
from modules.model_utils import ModelUtils
File "C:\RWKV\RWKV_Role_Playing\modules\model_utils.py", line 6, in <module>
from rwkv.model import RWKV
File "C:\Users\Momozawa Chiyuki\AppData\Local\Programs\Python\Python310\lib\site-packages\rwkv\model.py", line 29, in <module>
load(
File "C:\Users\Momozawa Chiyuki\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
return _jit_compile(
File "C:\Users\Momozawa Chiyuki\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
return _import_module_from_library(name, build_directory, is_python_module)
File "C:\Users\Momozawa Chiyuki\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1934, in _import_module_from_library
torch.ops.load_library(filepath)
File "C:\Users\Momozawa Chiyuki\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_ops.py", line 643, in load_library
ctypes.CDLL(path)
File "C:\Users\Momozawa Chiyuki\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Momozawa Chiyuki\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117\wkv_cuda\wkv_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by shengxia** [comment]
你试试这里面的方案
https://zhuanlan.zhihu.com/p/612879065

**Comment by leimm2002** [comment]
还是不行。
按照他说的下载了加速包、放进了对应目录、修改了model.py文件。还是同样的报错。
另外我在它报错指定的目录：
`C:\Users\Momozawa Chiyuki\AppData\Local\torch_extensions\torch_extensions\Cache\py310_cu117\wkv_cuda\wkv_cuda.pyd`
下是可以找到这个wkv_cuda.pyd的。
这是怎么回事呢？orz

**Comment by ASC8384** [comment]
一样的报错，但能找到相应目录下的`wkv_cuda.pyd`

**Comment by dengfenglai321** [comment]
RuntimeError: Error building extension 'wkv_cuda
一样的问题。

`In file included from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:7:0,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/Context.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/cuda/operators.cu:3:
/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/variant.h:243:2: error: #error "MPark.Variant requires C++11 support."
 #error "MPark.Variant requires C++11 support."
  ^
In file included from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/cuda/operators.cu:3:0:
/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++14 or later compatible compiler is required to use ATen.
 #error C++14 or later compatible compiler is required to use ATen.
  ^
In file included from /usr/include/c++/5/mutex:35:0,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:4,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/Context.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/cuda/operators.cu:3:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/string_view.h:4:0,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/StringUtil.h:6,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:6,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/Context.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/cuda/operators.cu:3:
/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
  ^
In file included from /usr/include/c++/5/experimental/string_view:39:0,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/string_view.h:20,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/StringUtil.h:6,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:6,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/Context.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/cuda/operators.cu:3:
/usr/include/c++/5/bits/c++14_warning.h:32:2: error: #error This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
 #error This file requires compiler and library support for the forthcoming \
  ^
In file included from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/Exception.h:7:0,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/Context.h:3,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                 from /data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/cuda/operators.cu:3:
/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/include/c10/util/variant.h:243:2: error: #error "MPark.Variant requires C++11 support."
 #error "MPark.Variant requires C++11 support."
  ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data8/dengfenglai/workpace/AIGC/RWKV_Role_Playing/webui.py", line 18, in <module>
    from modules.model_utils import ModelUtils
  File "/data8/dengfenglai/workpace/AIGC/RWKV_Role_Playing/modules/model_utils.py", line 6, in <module>
    from rwkv.model import RWKV
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/rwkv/model.py", line 29, in <module>
    load(
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data8/dengfenglai/anaconda/envs/sd-webui/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e`

**Comment by shengxia** [comment]
干脆直接装个最新版的visual studio吧。

**Comment by dengfenglai321** [comment]
> 干脆直接装个最新版的visual studio吧。

我的是linux

**Comment by shengxia** [comment]
> > 干脆直接装个最新版的visual studio吧。
> 
> 我的是linux

那就不知道了，我也最多就在colab上测试过，上面走的倒是挺顺利的。

**Comment by 3261647992** [comment]
同样错误

**Comment by 3261647992** [comment]
[3/3] "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64/link.exe" wrapper.o operators.cuda.o gemm_fp16_cublas.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\233\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\233\AppData\Local\Programs\Python\Python310\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\lib\x64" cudart.lib /out:wkv_cuda.pyd
FAILED: wkv_cuda.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64/link.exe" wrapper.o operators.cuda.o gemm_fp16_cublas.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\233\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\233\AppData\Local\Programs\Python\Python310\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\lib\x64" cudart.lib /out:wkv_cuda.pyd
这段输出显示编译扩展模块 wkv_cuda 失败了。从输出中可以看到编译器报告了链接错误。

关于 cuBLAS 的错误信息，特别是以下错误：

plaintext
Copy code
gemm_fp16_cublas.o : error LNK2019: 无法解析的外部符号 cublasCreate_v2
gemm_fp16_cublas.o : error LNK2019: 无法解析的外部符号 cublasGetMathMode
gemm_fp16_cublas.o : error LNK2019: 无法解析的外部符号 cublasSetMathMode
gemm_fp16_cublas.o : error LNK2019: 无法解析的外部符号 cublasGemmEx
gemm_fp16_cublas.o : error LNK2019: 无法解析的外部符号 cublasGemmStridedBatchedEx
这表明编译器无法解析 cuBLAS 的一些符号，这可能是由于链接参数或者路径配置不正确引起的。

**Comment by shengxia** [comment]
> 

这个看着像是rwkv这个库的问题，在某个版本会有这个问题，你试着更新一下，看看行不行。

**Comment by 3261647992** [comment]
更新了没有用

**Comment by shengxia** [comment]
嗯？？？？？不应该啊，我之前碰到了这个问题，它是刚开始碰到cuBLAS的问题，会停止编译，然后再重新编译一次，不过我的cuda是11.8，我不太确定是不是和这个有关。

**Comment by 3261647992** [comment]
> 嗯？？？？不应该啊，我之前仔细听过这个问题，是刚开始听cuBLAS的问题，会停止编译，然后再重新编译一次，不过我的cuda是11.8，我不太确定是不是和这个相关。

我用的是cuda 12.2，不知道跟这个有没有关系
