### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by exjhon** [shengxia/RWKV_Role_Playing#7]
已经安装了依赖项。

Traceback (most recent call last):
  File "D:\AI\Chat_RMKV\RWKV_Role_Playing-master\webui.py", line 20, in <module>
    from modules.ui import UI
  File "D:\AI\Chat_RMKV\RWKV_Role_Playing-master\modules\ui.py", line 2, in <module>
    import gradio as gr
  File "H:\ProgramData\Anaconda3\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "H:\ProgramData\Anaconda3\lib\site-packages\gradio\components.py", line 26, in <module>
    import matplotlib.figure
  File "H:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "H:\ProgramData\Anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "H:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "H:\ProgramData\Anaconda3\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by exjhon** [comment]
已自行解决，环境变量没配置好，丢人
